service: ${env:NAMESPACE}-app
frameworkVersion: "3"
configValidationMode: error
useDotenv: true
deprecationNotificationMode: warn:summary

package:
  patterns:
    - "!**"
    - "index.js"
    - "src/**"
    - "package.json"
    - "package-lock.json"

custom:
  stage: "${sls:stage}"
  namespace: "${env:NAMESPACE}"
  usersTableName: "${self:custom.namespace}-users-table-${self:custom.stage}"
  layersStackName: "${env:NAMESPACE}-layers-${sls:stage}"

provider:
  name: aws
  region: "${env:AWS_REGION}"
  profile: "${env:AWS_PROFILE}"
  tags:
    namespace: ${self:custom.namespace}
    service: ${self:service}
  stackTags:
    namespace: ${self:custom.namespace}
    service: ${self:service}
  deploymentMethod: changesets

  runtime: nodejs18.x
  memorySize: 512
  timeout: 6
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    NODE_PATH: "/opt/node_modules"
  # httpApi:
  #   disableDefaultEndpoint: true
  #   cors: true
  #   payload: "2.0"
  # authorizers:
  #   cognitoAuthorizer:
  #     identitySource: $request.header.Authorization
  #     issuerUrl: ${self:custom.userPoolIssuer}
  #     audience: ${self:custom.userPoolClientId}
  #     name: CognitoUserPoolAuthorizer
  #     resultTtlInSeconds: 300
  #     type: COGNITO_USER_POOLS

functions: ${file(./serverless/functions.yml)}

resources: ${file(./serverless/resources-cfn-template.yml)}
